### ISSUE TITLE
this doesn't seem right

### ISSUE THREAD

**Issue by alexge233** [alexge233/trump_make#10]
https://github.com/alexge233/trump_make/blob/a2cfe9ff55803d4267f395adb4169824844dcde4/dcgan.py#L75

Surely I need to calculate mean and std on the dataset, this hardecoded tensor seems wrong.
Maybe we can calculate the BGR std and mean programmatically?

**Comment by snehilchatterjee** [comment]
I propose modifying the code to calculate the mean and standard deviation of the dataset in batches during preprocessing. This would involve removing the current normalization step from the image folder function. Instead, I will calculate the mean and standard deviation dynamically in batches, ensuring that the normalization is based on the actual data rather than a predefined static value.

Once the mean and standard deviation are computed, I will reapply the image folder function using these newly calculated values.

Please let me know if this approach works for you, and I'd be happy to start implementing it.

**Comment by alexge233** [comment]
HI @snehilchatterjee yes by all means feel free. Bear in mind that branch `dev` probably holds the latest code since last time I worked on this.

**Comment by snehilchatterjee** [comment]
Sure, I will implement these changes in the latest code and open a pull request.

**Comment by snehilchatterjee** [comment]
I have opened a PR for the dev branch but it seems that it is behind master branch by 15 commits. Does this mean that master branch has the more updated code ? if so, should I also make the changes and open a PR for master branch ?

**Comment by alexge233** [comment]
@snehilchatterjee I am very sorry, I always use dev and then update master. Must have slipped up on this one. Please do the PR for master, ignore dev, if there's any conflicts I'll resolve them.

**Comment by snehilchatterjee** [comment]
Yeah man, no need to apologize. It's all good. I’ve raised the PR to the master branch with the same changes.
